version: "3.9"

services:
  omnibot_ros2:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_BASE_IMAGE: osrf/ros:jazzy-desktop-full
    container_name: omnibot_ros2
    network_mode: host
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ros2_ws:/workspaces/omnibot/ros2_ws
    working_dir: /workspaces/omnibot/ros2_ws
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiomem:/dev/gpiomem
      - /dev/i2c-1:/dev/i2c-1
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
      - /dev/mem:/dev/mem
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video5:/dev/video4
      - /dev/video4:/dev/video5
    command: >
      bash -lc "
      source /opt/ros/jazzy/setup.bash &&
      colcon build --symlink-install --packages-select &&
      source install/setup.bash &&
      sleep infinity
      "