# Transform Broadcaster Configuration
tf_broadcaster:
  ros__parameters:
    # Frame names
    base_frame: "base_link"
    odom_frame: "odom"
    lidar_frame: "lidar_link"
    
    # LIDAR position relative to base_link (x, y, z) in meters
    lidar_x: 0.0
    lidar_y: 0.0
    lidar_z: 0.1    # 10 cm above base
    lidar_angle: 210    # yaw rotation of lidar relative to base_link, in degreess