actuator_node:
  ros__parameters:
    # Параметры моторов
    motors:
      - pwm_ch: 0
        in1: 5
        in2: 6
      - pwm_ch: 1
        in1: 17
        in2: 22
      - pwm_ch: 2
        in1: 26
        in2: 27
    # Параметры сервоприводов
    servos:
      - channel: 4
        name: hand
        min_pulse: 0.75
        max_pulse: 2.25
      - channel: 5
        name: rotate
        min_pulse: 0.75
        max_pulse: 2.25
      - channel: 6
        name: grab
        min_pulse: 0.75
        max_pulse: 2.25
    # Общие настройки
    pca_frequency: 50        # Гц (50 для серв, подходит и для моторов)
    i2c_bus: 1
    i2c_address: 0x40
    gpio_chip: 4             # gpiochip4