controller_manager:
  ros__parameters:
    update_rate: 

    omni_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

omni_controller:
  ros__parameters:
    wheel_radius: 0.05
    wheel_separation_h: 0.15
    wheel_separation_v: 0.15
    
    wheels_per_side: 3
    wheel_positions: [0.0, 2.0944, 4.18879]

    odometry:
      publish_tf: true
      frame_id: odom
      child_frame_id: base_footprint

    linear:
      x:
        min: -1.0
        max: 1.0
    angular:
      z:
        min: -2.0
        max: 2.0